version: "3.8"

services:
  # dam-backend:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.dev
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - minio
  #     - redis

  postgres:
    image: postgres:16-alpine
    container_name: dam-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dam_backend
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: dam-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    volumes:
      - minio_data:/data

  redis:
    image: redis:7-alpine
    container_name: dam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  minio_data:
  redis_data:
