openapi: 3.0.0
info:
  title: DAM-backend API
  version: 1.0.0
  description: API documentation for DAM-backend application

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HealthResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Health check passed"
        data:
          type: object
          properties:
            status:
              type: string
              example: "OK"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "admin@dam.com"
        password:
          type: string
          format: password
          example: "Admin@123"

    LoginSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Login successful"
        data:
          type: object
          properties:
            token:
              type: string
              example: "jwt_token_here"
            user:
              type: object
              properties:
                id:
                  type: string
                  example: "uuid_here"
                full_name:
                  type: string
                  example: "Admin"
                email:
                  type: string
                  example: "admin@dam.com"
                role:
                  type: string
                  example: "ADMIN"

    InviteRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"

    InviteResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Invitation sent successfully"
        data:
          type: object
          properties:
            id:
              type: string
              example: "uuid_here"
            email:
              type: string
              example: "user@example.com"
            status:
              type: string
              example: "PENDING"
            invitedBy:
              type: string
              example: "uuid_of_admin"

    RegisterInviteRequest:
      type: object
      required:
        - email
        - password
        - invitationId
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          format: password
          example: "User@123"
        invitationId:
          type: string
          example: "uuid_of_invitation"

    RegisterInviteResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Registration successful"
        data:
          type: object
          properties:
            id:
              type: string
              example: "uuid_here"
            full_name:
              type: string
              example: "User Name"
            email:
              type: string
              example: "user@example.com"
            role:
              type: string
              example: "USER"

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Validation error

    PresignUploadRequest:
      type: object
      required:
        - filename
        - mime_type
        - size_bytes
      properties:
        filename:
          type: string
          description: Name of the file to upload
          example: dam.pdf
        mime_type:
          type: string
          description: MIME type or shorthand file type
          example: application/pdf
        size_bytes:
          type: integer
          description: Size of the file in bytes
          example: 1048576

    PresignUploadResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Presigned upload URL generated
        data:
          type: object
          properties:
            url:
              type: string
              description: Presigned S3 upload URL
              example: https://bucket-name.s3.amazonaws.com/assets/uuid/document.pdf?X-Amz-Algorithm=...
            asset_id:
              type: string
              description: ID of the created or reused asset
              example: "d3f6b8a1-4b90-4a38-bc9e-88e1e176f1a2"

    CompleteAssetResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Asset status updated to COMPLETED
        data:
          type: object
          properties:
            asset_id:
              type: string
              example: "uuid_here"
            status:
              type: string
              example: COMPLETED
            storage_path:
              type: string
              example: "uploads/file.pdf"
            uploader_id:
              type: string
              example: "uuid_of_uploader"

paths:
  /api/health:
    get:
      summary: Health check
      description: Returns service status
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /api/auth/login:
    post:
      summary: Login user
      description: Login using email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccessResponse"
        "400":
          description: Missing email or password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/invitations:
    post:
      summary: Invite a new user
      description: Send an invitation email to a new user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InviteRequest"
      responses:
        "200":
          description: Invitation sent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InviteResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/auth/register:
    post:
      summary: Register via invitation
      description: Complete registration for an invited user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterInviteRequest"
      responses:
        "200":
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterInviteResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/upload/presign:
    post:
      summary: Generate a presigned upload URL
      description: Returns a presigned S3 URL for uploading a file. Creates an asset record if it doesn't already exist.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PresignUploadRequest"
      responses:
        "200":
          description: Presigned upload URL generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PresignUploadResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized (missing or invalid token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Failed to generate presigned URL
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/upload/complete:
    post:
      summary: Complete asset upload
      description: Mark an uploaded asset as COMPLETED
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - asset_id
              properties:
                asset_id:
                  type: string
                  example: "uuid_here"
      responses:
        "200":
          description: Asset marked as COMPLETED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompleteAssetResponse"
        "400":
          description: Validation error or already completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Asset not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
