openapi: 3.0.0
info:
  title: DAM-backend API
  version: 1.0.0
  description: API documentation for DAM-backend application

# Security schemes
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

# This file will be processed by the build script
# The build script will merge all schemas and paths into a single swagger.yaml file
