FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Dev server with auto-reload
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/server.ts"]

EXPOSE 4000
